build:
  image: bjodah/bjodahimg18dev:v1.2
  commands:
    - python3 -m pip install git+https://github.com/bjodah/batemaneq.git
    - CPLUS_INCLUDE_PATH=$(python3 -c "import batemaneq; print(batemaneq.get_include())") ./run_all.sh
    - mkdir deploy
    - cp *.png deploy/

deploy:

  rsync:
    host: hera.physchem.kth.se
    user: decay-chain
    port: 22
    source: deploy/
    target: ~/public_html
    recursive: true
    delete: false
