image: bjodah/dockerfile-bjodah-scicomp
git:
    path: github.com/bjodah/decay-chain
script:
  - git clone -b fix_multiprecision_bulirsch_stoer --single-branch git://github.com/bjodah/odeint-v2.git odeint-v2-fix
  - ln -s odeint-v2-fix/include/boost boost
  - make
