image: bjodah/dockerfile-bjodah-scicomp
git:
    path: github.com/bjodah/decay-chain
script:
  - git clone --depth 1 git://github.com/headmyshoulder/odeint-v2.git
  - ln -s odeint-v2/include/boost boost
  - make
