clone:
  depth: 2
  recursive: true

build:
  image: bjodah/bjodahimg18dev:v1.2
  commands:
    - CPLUS_INCLUDE_PATH=$PWD/batemaneq/include ./run_all.sh
    - mkdir deploy
    - cp *.png deploy/

deploy:

  rsync:
    host: hera.physchem.kth.se
    user: decay-chain
    port: 22
    source: deploy/
    target: ~/public_html
    recursive: true
    delete: false
