build:
  image: bjodah/bjodahimg16dev:latest
  commands:
    - export CURPATH=$(pwd)
    - cd /opt/boost_1_63_0/boost/numeric/odeint/stepper
    - patch -p1 < $CURPATH/rosenbrock4_controller.hpp.patch
    - cd -
    - python -m pip install batemaneq
    - CPLUS_INCLUDE_PATH=/opt/boost_1_63_0:$(python -c "import batemaneq; print(batemaneq.get_include())") ./run_all.sh
    - mkdir deploy
    - cp *.png deploy/

deploy:

  rsync:
    host: hera.physchem.kth.se
    user: decay-chain
    port: 22
    source: deploy/
    target: ~/public_html
    recursive: true
    delete: false
